# Generated by Django 4.1.6 on 2023-11-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
