# Generated by Django 4.1.6 on 2023-12-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0010_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Đang chờ thanh toán'), ('SUCCESS', 'Thanh toán thành công'), ('FAILED', 'Thanh toán thất bại')], default='PENDING', max_length=20),
        ),
    ]
