# Generated by Django 4.1.6 on 2023-12-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0011_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Thẻ tín dụng'), ('BANK_TRANSFER', 'Chuyển khoản ngân hàng'), ('COD', 'Thanh toán khi nhận hàng'), ('MOMO', 'Thanh toán bằng Momo')], default='COD', max_length=20),
        ),
    ]
