# Generated by Django 4.1.6 on 2023-12-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0013_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
