# Generated by Django 4.1.6 on 2023-07-13 03:34

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_reset_usertoken_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.models.CustomUserManager()),
            ],
        ),
    ]
