# Generated by Django 4.1.6 on 2023-11-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
