# Generated by Django 4.1.6 on 2023-11-30 09:45

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_id_alter_useraddress_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.generate_filename),
        ),
    ]
