# Generated by Django 4.1.6 on 2023-06-24 04:20

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_image',
            field=models.ImageField(blank=True, upload_to=category.models.generate_filename),
        ),
    ]
