# Generated by Django 4.1.6 on 2023-06-24 04:05

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='Images',
            field=models.ImageField(blank=True, upload_to=store.models.generate_filename),
        ),
    ]
