# Generated by Django 4.1.6 on 2023-11-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_quantity_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
    ]
